<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->getChildHtml('head'); ?>
    <link href="<?php echo $this->getSkinUrl('css/jquery-filestyle.css') ?>" rel="stylesheet" type="text/css"/>
    <script src="http://jqueryvalidation.org/files/dist/jquery.validate.min.js"></script>
    <script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>
    <link href="<?php echo $this->getSkinUrl('css/dd.css') ?>" rel="stylesheet" type="text/css"/>
    <script src="<?php echo $this->getSkinUrl('js/countries.js') ?>"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body <?php echo $this->getBodyClass()?' class=" drawer drawer-left drawer-navbar drawer-fixed site-base drawer-close '.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('header'); ?>
<!--breadcrum/banner-->
<div class="main_con mrg-tp-var">
    <div class="container">
        <!--breadcrum-part-->
        <div class="breadcrum-con bg-grey">
            <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>
        </div>
        <!--/breadcrum-part-->
        <?php $cms_id = Mage::getSingleton('cms/page')->getIdentifier();
        $model = Mage::getModel('cms/page')->load($cms_id,'identifier');
        $media_path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
        ?>
        <?php  $route_url = Mage::app()->getRequest()->getRouteName();
        if( $route_url=="cms"){
            $pageHeading = $this->getLayout()->getBlock('page_content_heading')->toHtml();
            $pageHeading =  explode('#', $pageHeading);}
        ?>
        <?php if($model->getBanner()) { ?>
            <div class="banner-con custom-graphic-bnr"> <img src="<?php echo $media_path.$model->getBanner(); ?>"  alt="about-banner"/>
                <?php if($pageHeading) { ?>
                    <div class="custom-grapic-txtcon">
                        <h1><?php echo $pageHeading[0]; ?>
                            <span><?php echo $pageHeading[1]; ?></span></h1>
                        <p><?php echo $pageHeading[2]; ?></p>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>
<!--/breadcrum/banner-->
<!--middle-content-->
<div class="main_con">
    <div class="container">
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php  /* get cms page name */
        //$page = Mage::getModel('cms/page')->setStoreId(Mage::app()->getStore()->getId())->load('about-us');
        //$pageTitle = $page->getTitle();
        $cmsPageUrlKey = Mage::getSingleton('cms/page')->getIdentifier();
        ?>
        <?php if($route_url=="cms") { ?>
            <?php echo $this->getChildHtml('content'); ?>
        <?php }
        else { ?>
            <div class="srch-outercon">
                <?php echo $this->getChildHtml('content'); ?>
            </div>
        <?php } ?>
    </div>
</div>
<?php  if($cmsPageUrlKey=="about-us") {
    echo $this->getLayout()->createBlock('cms/block')->setBlockId('creative-services')->toHtml(); } ?>
<!--/middle-content-->
<!--newsletter-->
<div class="main_con bg-dk2e2e2e ">
    <div class="container">
        <div class="newsletter">
            <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
        </div>
    </div>
</div>
<!--/newsletter-->

<?php
if(isset($_POST['sample_order']))
{
    if(isset($_POST['g-recaptcha-response'])){
        $captcha=$_POST['g-recaptcha-response'];
    }
    if(!$captcha){
        $captchaerr = '<p>Please check the captcha form.</p>';
    }
    else {
        if($_POST['fname']==" " or $_POST['email']==" " or $_POST['zipcode']==" " or $_POST['address']==" " )
        {
            $pageURL = Mage::getUrl() . Mage::getSingleton('cms/page')->getIdentifier();
            Mage::app()->getFrontController()->getResponse()->setRedirect($pageURL);
        }
        else
        {
            $date = date("F j, Y, g:i a");
            $gen_contact = Mage::getStoreConfig('trans_email/ident_general/email');
            $to = $gen_contact;
            $subject = "Sample Order Request.";
            $txt = "First Name: ".$_POST['fname']."\n";
            $txt .= "Last Name: ".$_POST['lname']."\n";
            $txt .= "Email: ".$_POST['email']."\n";
            $txt .= "Company: ".$_POST['cmpy_name']."\n";
            $txt .= "Address: ".$_POST['address']."\n";
            $txt .= "Apt/Suite/Other: ".$_POST['aso']."\n";
            $txt .= "Country: ".$_POST['country_new']."\n";
            $txt .= "City: ".$_POST['city']."\n";
            if($_POST['intrntnal_ship']){
                $txt .= "State: ".$_POST['intrntnal_ship']."\n";
            }
            else{
                $_POST['intrntnal_ship'] = "";
            }

            if($_POST['state']){
                $txt .= "City/Province: ".$_POST['state']."\n";
            }
            else{
                $_POST['state'] = " ";
            }
            $txt .= "Zip Code: ".$_POST['zipcode']."\n";
            $txt .= "Shipping Cost: ".$_POST['shping_cost']."\n";
            $txt .= "Requested Stocks: ".$_POST['mssg']."\n";
            $headers = "From:". $_POST['email'];
            $mail_succes =  mail($to,$subject,$txt,$headers);
            if($mail_succes)
            {
                $write = Mage::getSingleton('core/resource')->getConnection('core_write');
                $writeMethods = get_class_methods(get_class($write));
                //foreach($writeMethods as $r){echo $r."\n";}
                $result = $write->insert(
                    "dealerinquiry",
                    array("firstname" => $_POST['fname'], "company" => $_POST['cmpy_name'],"address" => $_POST['address'],"taxvat" => $_POST['state'], "city" => $_POST['city'], "state" => $_POST['intrntnal_ship'], "country" => $_POST['country_new'], "zip" => $_POST['zipcode'], "email" => $_POST['email'], "storeid" => $_POST['shping_cost'],"website" => $_POST['form_name'], "desc" => $_POST['mssg'] , "iscustcreated" => 1, "date_time" => $date, "lstname" => $_POST['lname'], "aso" => $_POST['aso'])
                );
                $successUrl = Mage::getUrl('success_page');
                Mage::app()->getFrontController()->getResponse()->setRedirect($successUrl);
            }
        }
    }
}
?>
<?php echo $this->getChildHtml('footer'); ?>
<script src="<?php echo $this->getSkinUrl('js/dd.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.validate.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/additional-methods.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery-filestyle.js') ?>"></script>
<script type="text/javascript">
    //< ![CDATA[
    var myForm= new VarienForm('cGDesign', false);
    var myForm= new VarienForm('my-custom-form', false);
    //]]>
</script>
<script type="text/javascript">
    //   Validation.add('validate-email', 'Please enter a valid email address.', function(v) {
    //     return Validation.get('IsEmpty').test(v) || /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/i.test(v)
    // });

    Validation.add('validate-emailid', 'Please enter a valid email address.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/i.test(v)
    });
    Validation.add('validate-info', 'Please enter a comment of max 75 letters.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^[a-zA-Z][a-zA-Z0-9 -]{0,75}$/i.test(v)
    });

</script>

<script type="text/javascript">
    //< ![CDATA[
    var myForm= new VarienForm('oSPacket', false);
    //]]>
    jQuery(document).ready(function () {
        jQuery("#oSPacket").validate({
            rules: {
                country: {
                    required: true
                }
            }
        });
    });
</script>
<script type="text/javascript">
    jQuery( function() {
        jQuery(".slct-dropdown").msDropdown();
    });
</script>
<script type="text/javascript">
    jQuery('#brs-img2').jfilestyle({
        input: false
    });
</script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery( ".vv-state" ).hide();
        jQuery( ".vv-province" ).hide();
        var oDropdown = jQuery(".vv-country .slct-dropdown").msDropdown().data("dd");
        oDropdown.on("change", function() {
            var slectedvalue =  oDropdown.get("selectedText");
            if(slectedvalue == "USA")
            {
                jQuery( ".vv-state" ).show();
                jQuery( ".vv-province" ).hide();
                jQuery("#province").val('');
            }
            else
            {
                jQuery( ".vv-province" ).show();
                jQuery( ".vv-state" ).hide();
            }
        })
    });
</script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        var captcha = "<?php echo $captchaerr; ?>";
        if(captcha){
            jQuery( "div.captcharsult" ).html(captcha);
        }
    });
</script>
</body>
</html>