<!DOCTYPE html>

<html lang="en">

<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <meta charset="utf-8">

  <meta charset="utf-8">
  <?php $cmsPageUrlKey = Mage::getSingleton('cms/page')->getIdentifier();
  if($cmsPageUrlKey == "turn-around-times"){ ?>
  <title>Turn Around Times | Print for brands</title>
  <?php } elseif($cmsPageUrlKey == "shipping-information") { ?>
  <title>Shipping Information | Print for brands</title>
  <?php }
  elseif($cmsPageUrlKey == "return-policy") { ?>
  <title>Return Policy | Print for brands</title>
  <?php }
  ?>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php echo $this->getChildHtml('head'); ?>

  <link href='http://fonts.googleapis.com/css?family=Raleway:400,900,800,700,500,600,300,200,100' rel='stylesheet' type='text/css'>

  <link href="<?php echo $this->getSkinUrl('css/style.css') ?>" rel="stylesheet" type="text/css"/>

  <!-- drawer css -->

  <link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/drawer.min.css') ?>">

  <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/return-style.css') ?>">

  <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/turnaround-style.css') ?>">

  <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/privacy-style.css') ?>">

  <link href="<?php echo $this->getSkinUrl('css/bootstrap.css') ?>" rel="stylesheet" type="text/css"/>

  <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/dropdown.css') ?>">

  <link href="<?php echo $this->getSkinUrl('css/bootstrap-responsive.css') ?>" rel="stylesheet" type="text/css"/>

</head>





<body<?php echo $this->getBodyClass()?' class=" drawer drawer-left drawer-navbar drawer-fixed site-base drawer-close '.$this->getBodyClass().'"':'' ?>>



<?php echo $this->getChildHtml('header'); ?>



<!--breadcrum/banner-->



<div class="main_con mrg-tp-var">

  <div class="container">

    <!--breadcrum-part-->



    <div class="breadcrum-con bg-grey">

     <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>

   </div>

   <!--/breadcrum-part-->



 </div>

</div>



<!--/breadcrum/banner-->
<?php echo $this->getChildHtml('global_messages') ?>
<!--middle-content-->

<div class="main_con">

  <div class="container">

    <?php echo $this->getChildHtml('content'); ?>

  </div>

</div>





<!--/middle-content-->



<!--newsletter-->

<div class="main_con bg-dk2e2e2e ">

  <div class="container">

    <div class="newsletter">

     <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>

   </div>

 </div>

</div>

<!--/newsletter-->


<?php echo $this->getChildHtml('footer'); ?>

<script type="text/javascript">

    /* Start of jQuery to open & close collapsible list */
    jQuery(document).ready(function() {
        if( jQuery('#collapseOne').hasClass('in')){
            jQuery('#collapseOne').parent().children().addClass('opened').addClass('hdr-bgcolor');
        }
        jQuery('.rturn-ship-policy .accordion-body').on('show ',function(){
            jQuery(this).parent().children().addClass('opened').addClass('hdr-bgcolor');
        });
        jQuery('.rturn-ship-policy  .accordion-body').on('hide',function(){
            jQuery(this).parent().children().removeClass('opened').removeClass('hdr-bgcolor');
        });

    });
    /* End of jQuery to open & close collapsible list */

    /* Start of jQuery to scroll collapsible list for proper view */
    jQuery(document).ready(function(){
        jQuery('.rturn-ship-policy .accordion-body').on('shown ',function(){
            var deviceWidth = jQuery(window).width();
            /* Start of Screen Size above 986px */
            if(deviceWidth >= 986){
                var headerHeight = jQuery('header').height();
                var menuHeight = jQuery('.drawer-main').height();
                var topPadding = parseInt(jQuery('header').css('padding-top').replace("px", ""));
                var bottomPadding = parseInt(jQuery('header').css('padding-bottom').replace("px", ""));

                var totalHeight = headerHeight + menuHeight + topPadding + bottomPadding;
            }
            /* End of Screen Size above 986px */

            else if(deviceWidth < 986 && deviceWidth > 767){
                var headerHeight = jQuery('header').height();
                var menuHeight = jQuery('.drawer-main').height();
                var topPadding = parseInt(jQuery('header').css('padding-top').replace("px", ""));
                var bottomPadding = parseInt(jQuery('header').css('padding-bottom').replace("px", ""));

                var totalHeight = headerHeight + topPadding + bottomPadding;

            }

            else{
                var totalHeight = 0;

            }


            jQuery('html,body').animate({
                scrollTop: jQuery(this).closest('.accordion-group').offset().top-totalHeight
            });

        });
    });
    /* End of jQuery to scroll collapsible list for proper view */

</script>

</body>




</html>