<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta charset="utf-8">

<?php echo $this->getChildHtml('head'); ?>
 <!-- PAGINATION  -->
<script  src="<?php //echo $this->getSkinUrl('js/jquery-latest.js') ?>"></script>
 <!-- PAGINATION  -->
</head>


<body<?php echo $this->getBodyClass()?' class=" drawer drawer-left drawer-navbar drawer-fixed site-base drawer-close '.$this->getBodyClass().'"':'' ?>>

<?php echo $this->getChildHtml('header'); ?>

<!--breadcrum/banner-->

<div class="main_con mrg-tp-var">
  <div class="container">
    <!--breadcrum-part-->

    <div class="breadcrum-con bg-grey">
     <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>
    </div>
    <!--/breadcrum-part-->

  </div>
</div>

<!--/breadcrum/banner-->
<?php echo $this->getChildHtml('global_messages') ?>
<!--middle-content-->
<div class="main_con">
  <div class="container">

        <?php echo $this->getChildHtml('content'); ?>

  </div>
</div>


<!--/middle-content-->

<!--newsletter-->
<div class="main_con bg-dk2e2e2e ">
  <div class="container">
    <div class="newsletter">
         <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
    </div>
  </div>
</div>
<!--/newsletter-->

<?php echo $this->getChildHtml('footer'); ?>

<script type="text/javascript">
    equalheight = function( items2   ){
        var currentTallest = 0,
            currentRowStart = 0,
            rowDivs = new Array(),
            $el,
            topPosition = 0;
        jQuery( items2   ).each(function() {

            $el = jQuery(this);
            jQuery($el).height('auto')
            topPostion = $el.position().top;

            if (currentRowStart != topPostion) {
                for (currentDiv = 0 ; currentDiv < rowDivs.length ; currentDiv++) {
                    rowDivs[currentDiv].height(currentTallest);
                }
                rowDivs.length = 0; // empty the array
                currentRowStart = topPostion;
                currentTallest = $el.height();
                rowDivs.push($el);
            } else {
                rowDivs.push($el);
                currentTallest = (currentTallest < $el.height()) ? ($el.height()) : (currentTallest);
            }
            for (currentDiv = 0 ; currentDiv < rowDivs.length ; currentDiv++) {
                rowDivs[currentDiv].height(currentTallest);
            }
        });
    }

    jQuery(window).load(function() {
        equalheight('#items2  li');
    });
    jQuery(window).resize(function(){
        equalheight('#items2   li');
    });


</script>



</body>


</html>