<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="utf-8">

<meta charset="utf-8">

<!-- <title>Home | Print For Brands</title> -->

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<?php echo $this->getChildHtml('head') ?>


<!--style-->

<link href='http://fonts.googleapis.com/css?family=Raleway:400,900,800,700,500,600,300,200,100' rel='stylesheet' type='text/css'>

<link href="<?php echo $this->getSkinUrl('css/style.css') ?>" rel="stylesheet" type="text/css"/>

<!-- drawer css -->

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/drawer.min.css') ?>">

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/home-style.css') ?>">

<link href="<?php echo $this->getSkinUrl('css/bootstrap.css') ?>" rel="stylesheet" type="text/css"/>

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/dropdown.css') ?>">

<link href="<?php echo $this->getSkinUrl('css/bootstrap-responsive.css') ?>" rel="stylesheet" type="text/css"/>

<!--/style-->
    <!--<script type="text/javascript" src="<?php /*echo $this->getSkinUrl('js/jquery.js') */?>"></script>-->
<!--<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="http://jqueryvalidation.org/files/dist/jquery.validate.min.js"></script>
    <script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>-->
</head>

<body<?php echo $this->getBodyClass()?' class=" drawer drawer-left drawer-navbar drawer-fixed site-base drawer-close '.$this->getBodyClass().'"':'' ?>>

<?php

  if(isset($_POST['askQues']))
       {

          if(isset($_POST['g-recaptcha-response'])){
            $captcha=$_POST['g-recaptcha-response'];
          }
          if(!$captcha){
            $captchaerr = '<p class="ask_error" style="color: #ff0000">Check box if you are not a robot.</p>';
             }
          else{
          			$gen_contact = Mage::getStoreConfig('trans_email/ident_general/email');

                   $to = $gen_contact;

                    $subject = "Ask a Question.";

                    $txt  = "Name: ".$_POST['fName']."\n";

                    $txt .= "Email: ".$_POST['fEmail']."\n";

                    $txt .= "Message: ".$_POST['fMessage']."\n";

                    $headers = "From:". $_POST['fEmail'];

                    mail($to,$subject,$txt,$headers);

                   $write = Mage::getSingleton('core/resource')->getConnection('core_write');

                   $writeMethods = get_class_methods(get_class($write));

                   $result = $write->insert(

                   "dealerinquiry",

                   array("firstname" => $_POST['fName'],"email" => $_POST['fEmail'], "form" => $_POST['formName'], "message" => $_POST['fMessage'] )

                  );
                  //Mage::getSingleton('customer/session')->addSuccess('Thanks for contacting us, we will get back to you soon');
                 Mage::app()->getFrontController()->getResponse()->setRedirect('success_page')->sendResponse();
              }
       }

?>

<!--ask a question-->

<div class="askcon-fix">

<div id="pd-fx" class="pos_fix">

   <a class="in-quick" " id="contact"><img src="<?php echo $this->getSkinUrl('img/ask-txt-ques.jpg') ?>"  alt="ask-txt"/></a>

</div>

<div class="contact_open">



  <div id="contact1" class="inquiry-form hide">

  <div class="askimg_left"> <img src="<?php echo $this->getSkinUrl('img/ask-txt-ques.jpg') ?>"  alt="ask-txt"/></div>

    <div id="contact2"><a class="str_close">x</a></div>

    <div class="form-inner">

      <form method="post" id="ask-form" onsubmit="return validateform();">
        <span><?php //echo $captchaerr; ?></span>
        <div class="form-control">

          <input type="text" placeholder=" Name" maxlength="50" class="required-entry validate-name txt-field " value= "<?php echo $_POST['fName']; ?>"name="fName">

          <span class="txt-fld person"></span></div>

        <div class="form-control">

          <input type="text" placeholder="Email" maxlength="50" class="required-entry validate-emailid txt-field" value= "<?php echo $_POST['fEmail']; ?>" name="fEmail">

          <span class="txt-fld  email"></span></div>

        <div class="form-control">

          <textarea placeholder="Message" maxlength="100" class="txt-area required-entry" value= "<?php echo $_POST['fMessage']; ?>" name="fMessage"><?php echo htmlspecialchars($_POST['fMessage']);?></textarea>

          <span class=" txt-fld txtarea-fld"></span></div>

        <div class="captcha-fld">
              <div class="g-recaptcha" data-sitekey="6LfmyB4TAAAAAKnRG-pri2okMiatW2TmLx8XmFIU"></div>
			  <span style="color:red; font-size: 11px;" id="demo"><?php echo $captchaerr; ?></span>
        </div>

        <input type="hidden" name="formName" value="Ask a Question">

        <div class="frm-btn">

          <input type="submit" value="Submit" class="submit-btn" name="askQues">

        </div>

      </form>

    </div>

  </div>

</div>

</div>

<!--/ask a question-->



<?php echo $this->getChildHtml('header') ?>



<!--slider-part-->

<div class="main_con bg-drkgrey mrg-tp-var">

  <div class="container">



    <div class="main-slider">

        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_slider')->toHtml(); ?>

    </div>

  </div>

</div>

<!--slider-part-->

<!--middle-content-->
<?php echo $this->getChildHtml('global_messages') ?>
<div class="main_con">

  <div class="container">

    <div class="feature-con">

      <h3>Featured <span>Products</span></h3>

      <div class="row-fluid">

      <?php

            $category = Mage::getModel('catalog/category')->load(48);

            $collection = $category->getProductCollection();

            $collection->addAttributeToSelect('name');

            $collection->addAttributeToSelect('description');

            $collection->addAttributeToSelect('thumbnail');

            $collection->addAttributeToSelect('url');

            $collection->addAttributeToSelect('price');

            $catUrl = $category->getUrl();



            $products = $collection->getItems();

            foreach ($products as $product) {

              //echo $product->getPrice();

              // $_formattedActualPrice = Mage::helper('core')->currency($product->getPrice(),true,false); getting price with currency sign

              //echo $_formattedActualPrice;

              $currney=Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();

              $price=round($product->getPrice(),0);

              $productDes = explode('#',$product->getDescription());

      ?>

        <div class="span3">



          <div class="feature-options"><img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail'); ?>"  alt=""/>

            <div class="feature-detail">

              <h2><?php echo $productDes[0]; ?>
              <span><?php echo $productDes[1]; ?></span><?php echo $productDes[2]; ?></h2>

              <div class="price-tag"><?php echo $currney.$price; ?></div>

            </div>

            <?php  $productUrl = basename($product->getProductUrl());?>

            <a href="<?php echo $catUrl.'/'.$productUrl; ?>" class="choose-btn">choose</a> </div>

        </div>

        <?php } ?>

      </div>

      <div class="feature-banner-con">

        <div class="row-fluid">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('feature-banner1')->toHtml(); ?>
        </div>

      </div>

    </div>

  </div>

</div>

<!--/middle-content-->

<!--newsletter-->

<div class="main_con bg-dk2e2e2e ">

  <div class="container">

    <div class="newsletter">

         <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>

    </div>

  </div>

</div>

<!--/newsletter-->


<?php echo $this->getChildHtml('footer') ?>

<!-- bx slider-->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.bxslider.min.js') ?>"></script>
<script type="text/javascript">var jq1_9_1 = jQuery.noConflict();</script>

<script>

jq1_9_1(document).ready(function() {

  jq1_9_1('.bxslider').bxSlider({
 pager:true,
 controls:false,
 auto:true
});
});

</script>
<!--sliding_ask_question -->

<script type="text/javascript">
    jq1_9_1(document).ready(function(){
        jq1_9_1("#pd-fx, #contact").click(function(){
            jq1_9_1("#contact1").show("slide",{direction: "right" },500 );
            jq1_9_1("#pd-fx, #contact").hide();
            jq1_9_1('form')[0].reset();
            jq1_9_1('.validation-advice').remove();
            jq1_9_1('#demo').empty();
            return false;
        });

        jq1_9_1("#contact2").click(function(){
            jq1_9_1("#contact1").hide( "slide",
                { direction: "right"},500,function(){
                    jq1_9_1("#pd-fx, #contact").show();
                });
            return false;
        });

        if(jq1_9_1("#ask-form .ask_error").length > 0)
        {
            //alert('ok');
            jq1_9_1("#contact1").show("slide",{direction: "right" },500);
            jq1_9_1("#pd-fx, #contact").hide();
            jq1_9_1('form')[0].reset();
            jq1_9_1('.validation-advice').remove();
            jq1_9_1('#demo').empty();
            return false;
        }

    });

    Validation.add('validate-name', 'Please use letters or numbers only.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(?=.*[a-zA-Z].*)([-_a-zA-Z0-9 ]+)$/i.test(v)
    });

    Validation.add('validate-emailid', 'Please enter a valid email address.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/i.test(v)
    });

</script>

<script type="text/javascript">
    //< ![CDATA[
       var myForm= new VarienForm('ask-form', false);
    //]]>
</script>
<script type="text/javascript">
    function validateform(){
        var captcha_response = grecaptcha.getResponse();
        if(captcha_response.length == 0)
        {
            // Captcha is not Passed
            document.getElementById("demo").innerHTML = "Please fill captcha!";
            return false;
        }
        else if(captcha_response.length != 0)
        {
            // Captcha is not Passed
            document.getElementById("demo").innerHTML = "";
            return true;
        }
        else
        {
            // Captcha is Passed
            return true;
        }
    }
    // ]]>
</script>
</body>


</html>