<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->getChildHtml('head'); ?>
    <link href="<?php echo $this->getSkinUrl('css/jquery-filestyle.css') ?>" rel="stylesheet" type="text/css"/>
    <script src="http://jqueryvalidation.org/files/dist/jquery.validate.min.js"></script>
    <script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>
    <link href="<?php echo $this->getSkinUrl('css/dd.css') ?>" rel="stylesheet" type="text/css"/>
    <script src="<?php echo $this->getSkinUrl('js/countries.js') ?>"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>

</head>
<body class="drawer drawer-left drawer-navbar drawer-fixed site-base drawer-close">
<?php echo $this->getChildHtml('header'); ?>
<!--breadcrum/banner-->
<div class="main_con mrg-tp-var">
    <div class="container">
        <!--breadcrum-part-->
        <div class="breadcrum-con bg-grey">
            <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>
        </div>
        <!--/breadcrum-part-->
        <?php $cms_id = Mage::getSingleton('cms/page')->getIdentifier();
        $model = Mage::getModel('cms/page')->load($cms_id,'identifier');
        $media_path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
        ?>
        <?php  $route_url = Mage::app()->getRequest()->getRouteName();
        if( $route_url=="cms"){
            $pageHeading = $this->getLayout()->getBlock('page_content_heading')->toHtml();
            $pageHeading =  explode('#', $pageHeading);}
        ?>
        <?php if($model->getBanner()) { ?>
            <div class="banner-con custom-graphic-bnr"> <img src="<?php echo $media_path.$model->getBanner(); ?>"  alt="about-banner"/>
                <?php if($pageHeading) { ?>
                    <div class="custom-grapic-txtcon">
                        <h1><?php echo $pageHeading[0]; ?>
                            <span><?php echo $pageHeading[1]; ?></span></h1>
                        <p><?php echo $pageHeading[2]; ?></p>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>
<!--/breadcrum/banner-->

<?php

if(isset($_POST['sample_order']))
{
    if(isset($_POST['g-recaptcha-response']))
    {
        $captcha=$_POST['g-recaptcha-response'];
    }
    if(empty($captcha))
    {
        $captchaerr = 'Check box if you are not a robot.';
    }
    else
    {
        if($_POST['fname']==" " or $_POST['email']==" " or $_POST['zipcode']==" " or $_POST['address']==" " )
        {
            $pageURL = Mage::getUrl() . Mage::getSingleton('cms/page')->getIdentifier();
            Mage::app()->getFrontController()->getResponse()->setRedirect($pageURL);
        }
        else
        {
            // to send mail
            // $gen_contact = Mage::getStoreConfig('trans_email/ident_general/email');
            // $to = $gen_contact;
            if($_POST['country_new'] == "US")
            {
                $shipping = "US Shipping - $10";
            }
            else
            {
                $shipping = "International Shipping - $20";
            }
            $to = "print4brands@gmail.com";
            $subject = "Custom Sample Order Request";
            $txt = '<html><body>';
            $txt .= '<img src="http://printforbrands.webreinvent.com/skin/frontend/default/printforbrand/img/logo.png" alt="PrintForBrands"> ';
            $txt .= '<h2>You have received a new order.<h2>';
            $txt .= '<table rules="all" style="border-color: #666;" cellpadding="10">';
            $txt .= "<tr style='background: #eee;'><td><strong>First Name:</strong> </td><td>" . strip_tags($_POST['fname']) . "</td></tr>";
            $txt .= "<tr><td><strong>Last Name:</strong> </td><td>" . strip_tags($_POST['lname']) . "</td></tr>";
            $txt .= "<tr><td><strong>Email:</strong> </td><td>" . strip_tags($_POST['email']) . "</td></tr>";
            $txt .= "<tr><td><strong>Company:</strong> </td><td>" . strip_tags($_POST['cmpy_name']) . "</td></tr>";
            $txt .= "<tr><td><strong>Address:</strong> </td><td>" . strip_tags($_POST['address']) . "</td></tr>";
            $txt .= "<tr><td><strong>Apt/Suite/Other:</strong> </td><td>" . strip_tags($_POST['aso']) . "</td></tr>";
            $txt .= "<tr><td><strong>Country:</strong> </td><td>" . $_POST['country_new'] . "</td></tr>";

            if($_POST['country_new'] == 'US')
            {
                if(!empty($_POST['state_new']))
                {
                    $_POST['state'] = $_POST['state_new'];
                }
                else{
                    $_POST['state'] = " ";
                }

            }
            $txt .= "<tr><td><strong>State:</strong> </td><td>" . $_POST['state'] . "</td></tr>";
            $txt .= "<tr><td><strong>City:</strong> </td><td>" . $_POST['city'] . "</td></tr>";
            $txt .= "<tr><td><strong>Zipcode:</strong> </td><td>" . $_POST['zipcode'] . "</td></tr>";
            $txt .= "<tr><td><strong>Shipping Cost:</strong> </td><td>" . $shipping . "</td></tr>";
            $txt .= "<tr><td><strong>Requested Stocks:</strong> </td><td>" . $_POST['mssg'] . "</td></tr>";

            $txt .= "</table>";
            $txt .= "</body></html>";
            $headers = "From: " . strip_tags($_POST['email']) . "\r\n";
            $headers .= "Reply-To: ". strip_tags($_POST['email']) . "\r\n";
            //$headers .= "CC: susan@example.com\r\n";
            $headers .= "MIME-Version: 1.0\r\n";
            $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
            $success_mail = mail($to,$subject,$txt,$headers);

            if($success_mail)
            {
                $to = $_POST['email'];
                $from = 'print4brands@gmail.com';
                $headers = "From: " . $from . "\r\n";
                $headers .= "Reply-To: ". $from . "\r\n";
                //$headers .= "CC: susan@example.com\r\n";
                $headers .= "MIME-Version: 1.0\r\n";
                $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
                $subject ="Confirmation mail from Printforbrands";
                $msg = '<img src="http://printforbrands.webreinvent.com/skin/frontend/default/printforbrand/img/logo.png" alt="PrintForBrands"> ';
                $msg .= '<h2>Thanks for contacting us, we will get back to you soon.</h2>';
                $success_mail1 = mail($to,$subject,$msg,$headers);
            }

            if($success_mail1)
            {
                $write = Mage::getSingleton('core/resource')->getConnection('core_write');
            }
            //$writeMethods = get_class_methods(get_class($write));
//foreach($writeMethods as $r){echo $r."\n";}

            $result = $write->insert("dealerinquiry", array(
                    "firstname" => $_POST['fname'],
                    "lstname" => $_POST['lname'],
                    "company" => $_POST['cmpy_name'],
                    "address" => $_POST['address'],
                    "country" => $_POST['country_new'],
                    "state" => $_POST['state'],
                    "city" => $_POST['city'],
                    "zip" => $_POST['zipcode'],
                    "email" => $_POST['email'],
                    "desc" => $_POST['mssg'],
                    "website" => $_POST['form_name'],
                    "iscustcreated" => 1,
                    "date_time" => $date,
                    "aso" => $_POST['aso']
                )
            );

            $successUrl = Mage::getUrl('success_page');
            Mage::app()->getFrontController()->getResponse()->setRedirect($successUrl);

        }
    }
}

?>
<?php echo $this->getChildHtml('global_messages') ?>
<!--middle-content-->
<div class="main_con">
    <div class="container">
        <div class="free-samplecon">
            <?php echo $this->getChildHtml('content') ?>
            <div class="sampletemplate-form">
                <h3>Get <strong>Samples</strong></h3>
                <div class="sample-inrform">
                    <form id="oSPacket" method="post" name="order_sample_packet_form" action="<?php echo $_SERVER['PHP_SELF']; ?>" onsubmit="return validateform();">

                        <div class="input-field"><label>First Name<sup>*</sup></label>
                            <div class="inp-text"><input id="fname" class="inp-text-inpt required-entry validate-name" type="text" value="<?php echo $_POST['fname']; ?>" maxlength="20" placeholder="Enter your First Name" name="fname" /></div>
                        </div>
                        <div class="input-field"><label>Last Name<sup>*</sup></label>
                            <div class="inp-text"><input id="lname" class="inp-text-inpt required-entry validate-name" type="text" value="<?php echo $_POST['lname']; ?>" maxlength="20" placeholder="Enter your Last Name" name="lname" /></div>
                        </div>
                        <div class="input-field"><label>Company</label>
                            <div class="inp-text"><input id="cmpy_name" class="inp-text-inpt " type="text" value="<?php echo $_POST['cmpy_name']; ?>" maxlength="30" placeholder="Enter Company Name" name="cmpy_name" /></div>
                        </div>
                        <div class="input-field"><label>Street Address<sup>*</sup></label>
                            <div class="inp-text"><input id="address" class="inp-text-inpt required-entry" type="text" value="<?php echo $_POST['address']; ?>" maxlength="50" placeholder="Enter your Address" name="address" /></div>
                        </div>
                        <div class="input-field"><label>Apt/Suite/Other</label>
                            <div class="inp-text"><input id="aso" class="inp-text-inpt " type="text" value="<?php echo $_POST['aso']; ?>" placeholder="Enter your Apt/Suite/Other" maxlength="50" name="aso" /></div>
                        </div>
                        <div class="input-field"><label>Country<sup>*</sup></label>
                            <div class="inp-text">
                                <?php $_countries = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false) ?>
                                <?php if (count($_countries) > 0): ?>
                                    <select name="country_new" class="chosen-select required-entry" id="country_new" style="width: 100%;">
                                        <!-- <option value="">– Please Select –</option>   -->
                                        <?php if($_POST['sample_order'] == true && $_POST['country_new'] != ""){ ?>
                                            <option value="<?php echo $_POST['country_new']; ?>" selected="selected"><?php echo $_POST['country_new']; ?></option>
                                        <?php }else{ ?>
                                            <option value=""> – Please Select – </option>
                                        <?php } ?>
                                        <?php foreach($_countries as $_country): ?>
                                            <option value="<?php echo $_country['value'] ?>">
                                                <?php echo $_country['label'] ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                <?php endif; ?>


                            </div>
                        </div>

                        <div class="input-field"><label>State/Province<sup>*</sup></label>
                            <div class="inp-text">

                                <input id="state" class="inp-text-inpt validate-state" type="text" maxlength="20" value="<?php echo $_POST['state']; ?>" placeholder="State/Province" name="state" />

                                <select id="region_id" style="display:none;" style="width:100%;" name="state_new" title="<?php echo $this->__('State/Province') ?>" class="chosen-select">
                                    <option value=""><?php echo $this->__('Please select state or province') ?></option>
                                    <?php
                                    $regions = Mage::getModel('directory/country')->load('US')->getRegions();
                                    foreach($regions as $region)
                                    {
                                        echo "<option value=".$region[name].">".$region['name'] . "</option>";
                                    }
                                    ?>
                                </select>
                            </div>

                        </div>

                        <div class="input-field"><label>City<sup>*</sup></label>
                            <div class="inp-text"><input id="city" class="inp-text-inpt required-entry validate-city" type="text" value="<?php echo $_POST['city']; ?>" placeholder="Enter your City" maxlength="20" name="city" /></div>
                        </div>
                        <!--    <div class="input-field vv-state"><label>State<sup>*</sup></label>
                               <div class="inp-text"><select id="state" value="state" class="chosen-select validate-select" style="width: 100%;" name="intrntnal_ship"></select>
                                   <script type="text/javascript">// <![CDATA[
                                       print_country("country");
                                       // ]]></script>
                               </div>
                           </div> -->
                        <div class="input-field"><label>Zip Code<sup>*</sup></label>
                            <div class="inp-text"><input id="zipcode" class="inp-text-inpt required-entry validate-zipcode" type="text" value="<?php echo $_POST['zipcode']; ?>" maxlength="10" placeholder="Enter zip code" name="zipcode" /></div>
                        </div>
                        <div class="input-field"><label>Email<sup>*</sup></label>
                            <div class="inp-text"><input id="email" class="inp-text-inpt required-entry validate-emailid" type="text" value="<?php echo $_POST['email']; ?>" maxlength="50" placeholder="Enter your Email" name="email" /></div>
                        </div>
                        <div class="input-field"><label>Requested Stocks</label>
                            <div class="inp-text"><textarea id="mssg" class="inp-txt-area" name="mssg" maxlength="500" placeholder="Please list stocks as you would like to see in your sample packet"><?php echo $_POST['mssg']; ?></textarea></div>
                        </div>
                        <div class="input-field vv-shippingcost">
<!--                            <label>Shipping Cost<sup>*</sup></label>-->
                            <div class="inp-text">
<!--                                <select class="chosen-select required-entry validate-select" style="width: 100%;" name="shping_cost">-->
<!--                                    <option value="">Choose Packets</option>-->
<!---->
<!--                                    <option value=""> Choose Packets </option>-->

<!--                                    <option "--><?php //if($_POST['shping_cost'] == "US Shipping-$10"){ ?><!--" selected "--><?php //}?><!--" value="US Shipping-$10">US Shipping-$10</option>-->
<!--                                    <option "--><?php //if($_POST['shping_cost'] == "International Shipping-$15"){ ?><!--" selected "--><?php //}?><!--" value="International Shipping-$15">International Shipping-$15</option>-->
<!--                                </select>-->
                            </div>
                            <input class="inp-text" type="hidden" value="Order Sample Packet" name="form_name" />
                            <div class="input-field">&nbsp;</div>
                            <p><strong>NOTE:</strong> US sample packets will be $10, International will be $15. Free ground shipping.</p>
                        </div>
                        <div class="input-field captcha-fld"><label><p></p></label>


                            <div class="inp-text">
                                <!--<div class="g-recaptcha" data-sitekey="6LfmyB4TAAAAAKnRG-pri2okMiatW2TmLx8XmFIU"></div>-->
                                <div class="g-recaptcha" data-sitekey="6LfmyB4TAAAAAKnRG-pri2okMiatW2TmLx8XmFIU" data-callback="onReturnCallback" data-theme="light"></div>
                                <span style="color:red;" id="demo"><?php echo $captchaerr; ?></span>
                            </div>


                        </div>
                        <div class="form-submit">&nbsp;</div>
                        <div class="form-submit"><input class="submit-btn" type="submit" value="Submit Sample Order" name="sample_order" /></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--/middle-content-->

<!--newsletter-->
<div class="main_con bg-dk2e2e2e ">
    <div class="container">
        <div class="newsletter">
            <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
        </div>
    </div>
</div>
<!--/newsletter-->
<!--footer-->
<?php echo $this->getChildHtml('footer'); ?>
<!--/footer-->
<script src="<?php echo $this->getSkinUrl('js/dd.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.validate.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/additional-methods.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery-filestyle.js') ?>"></script>

<script type="text/javascript">

    var jqm26 = jQuery.noConflict();

    jqm26(document).ready(function () {
        var deviceWidth26 = jqm26(document).width();
        jqm26('form').on('click','.submit-btn',function(){
            if(deviceWidth26 >= 768) {
                var topMargin = jqm26(this).closest('body').find('.mrg-tp-var').css('margin-top');
                /*alert(topMargin);*/
                var scrollDiv2 = jqm26(this).closest('form').find('.validation-advice');
                if(scrollDiv2.length == 0){
                    scrollDiv2 = jqm26(this).closest('form').find('.inp-text-inpt');
                }
                jqm26("html, body").animate({
                    scrollTop: jqm26(scrollDiv2).offset().top-250
                });
            }
            else {
                var topMargin = jqm26(this).closest('body').find('.mrg-tp-var').css('margin-top');
                var scrollDiv2 = jqm26(this).closest('form').find('.validation-advice');
                if(scrollDiv2.length == 0){
                    scrollDiv2 = jqm26(this).closest('form').find('.inp-text-inpt');
                }
                jqm26("html, body").animate({
                    scrollTop: jqm26(scrollDiv2).offset().top
                });
            }
        });
    });

</script>

<script type="text/javascript">
    Validation.add('validate-name', 'Please use letters only, numbers are optional.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(?=.*[a-zA-Z].*)([-_a-zA-Z0-9 ]+)$/i.test(v)
    })
    Validation.add('validate-zipcode', 'Please enter valid zipcode.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^[a-zA-Z0-9 -]*$/i.test(v)
    })
    Validation.add('validate-emailid', 'Please enter a valid email address.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/i.test(v)
    });
    Validation.add('validate-city', 'Please enter a valid city.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(?:[a-zA-Z]+(?:[.'\-,])?\s?)+$/i.test(v)
    })
    Validation.add('validate-state', 'Please enter valid state.', function(v) {
        return Validation.get('IsEmpty').test(v) || /[a-zA-Z0-9-)(.' ]$/i.test(v)
    })
</script>
<script type="text/javascript">
    //< ![CDATA[
    var myForm= new VarienForm('oSPacket', false);
    //]]>
    jQuery(document).ready(function () {
        jQuery("#oSPacket").validate({
            rules: {
                country: {
                    required: true
                }
            }
        });
    });
</script>
<script type="text/javascript">
    jQuery( function() {
        jQuery(".slct-dropdown").msDropdown();
    });
</script>
<script type="text/javascript">
    jQuery('#brs-img2').jfilestyle({
        input: false
    });
</script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery( ".vv-state" ).hide();
        jQuery( ".vv-province" ).hide();
        var oDropdown = jQuery(".vv-country .slct-dropdown").msDropdown().data("dd");
        oDropdown.on("change", function() {
            var slectedvalue =  oDropdown.get("selectedText");
            if(slectedvalue == "USA")
            {
                jQuery( ".vv-state" ).show();
                jQuery( ".vv-province" ).hide();
                jQuery("#province").val('');
            }
            else
            {
                jQuery( ".vv-province" ).show();
                jQuery( ".vv-state" ).hide();
            }
        })
    });
</script>
<!--<script type="text/javascript">
    jQuery(document).ready(function(){
        var captcha = "<?php /*echo $captchaerr; */?>";
        if(captcha){
            jQuery( "div.captcharsult" ).html(captcha);
        }
    });
</script>-->

<script type="text/javascript" language="javascript">
    function validateform(){
        var captcha_response = grecaptcha.getResponse();
        if(captcha_response.length == 0)
        {
            // Captcha is not Passed
            document.getElementById("demo").innerHTML = "Please Fill captcha!";
            return false;
        }
        else if(captcha_response.length != 0)
        {
            document.getElementById("demo").innerHTML = "";
            return true;
        }
        else
        {
            // Captcha is Passed
            return true;
        }
    }
    // ]]>
</script>

</body>
</html>