<?php   $currentUrl1 = Mage::helper('core/url')->getCurrentUrl(); ?>

<?php $str = '?';

$currentUrl = substr($currentUrl1,0,strrpos($currentUrl1,'?'));

?>

<?php $cssurl =  str_replace('index.php/','',$this->getUrl());?>

<?php    $gallery_status=$this->getImagegalleryEnabled();   ?>

<?php    $gallery_Paggingstar=$this->getImagegalleryPaggingstart();   ?>

<?php    $gallery_Rowitem=$this->getImagegalleryRowitem(); ?>

<?php    $gallery_imageheight = $this->getImagegalleryimageheight(); ?>

<?php    $gallery_imagewwidth = $this->getImagegalleryimagewidth(); ?>

<?php    $gallery_popuphight = $this->getImagegalleryvideohight(); ?>

<?php    $gallery_popupwidth = $this->getImagegalleryvideowidth(); ?>

<?php    $gallery_popupspeed = $this->getImagegallerypopupspeed(); ?>

<?php    $gallery_type = $this->getImagegallerytype(); ?>

<?php    $sql = $this->getImagegallerysql(); ?>


<?php  if($gallery_status==1){

/* check module status */

 ?>

<?php



 if($gallery_type=='1'){ ?>







<?php

$connection = Mage::getSingleton('core/resource')->getConnection('core_write');

$prefix = Mage::getConfig()->getTablePrefix();

$tblname=$prefix.'popupgalleryslider';

$nr = $connection->fetchOne( "SELECT COUNT(*) AS count FROM $tblname" );

//$sql = mysql_query("SELECT * FROM imagegallery");



//echo $nr = mysql_num_rows($sql); // Get total of Num rows from the database query

if (isset($_GET['pn']))
{ // Get pn from URL vars if it is present
    $pn = preg_replace('#[^0-9]#i', '', $_GET['pn']);
    // filter everything but numbers for security(new)
}
else
{
    $pn = 1;
    }



$itemsPerPage = $gallery_Paggingstar;



$lastPage = ceil($nr / $itemsPerPage);



if ($pn < 1) { // If it is less than 1

    $pn = 1; // force if to be 1

} else if ($pn > $lastPage) { // if it is greater than $lastpage

    $pn = $lastPage; // force it to be $lastpage's value

}

// This creates the numbers to click in between the next and back buttons

// This section is explained well in the video that accompanies this script

$centerPages = "";

$sub1 = $pn - 1;

$sub2 = $pn - 2;

$add1 = $pn + 1;

$add2 = $pn + 2;

if ($pn == 1) {

    $centerPages .= '&nbsp; <span class="pagNumActive">' . $pn . '</span> &nbsp;';

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $add1 . '">' . $add1 . '</a> &nbsp;';

} else if ($pn == $lastPage) {

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $sub1 . '">' . $sub1 . '</a> &nbsp;';

    $centerPages .= '&nbsp; <span class="pagNumActive">' . $pn . '</span> &nbsp;';

} else if ($pn > 2 && $pn < ($lastPage - 1)) {

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $sub2 . '">' . $sub2 . '</a> &nbsp;';

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $sub1 . '">' . $sub1 . '</a> &nbsp;';

    $centerPages .= '&nbsp; <span class="pagNumActive">' . $pn . '</span> &nbsp;';

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $add1 . '">' . $add1 . '</a> &nbsp;';

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $add2 . '">' . $add2 . '</a> &nbsp;';

} else if ($pn > 1 && $pn < $lastPage) {

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $sub1 . '">' . $sub1 . '</a> &nbsp;';

    $centerPages .= '&nbsp; <span class="pagNumActive">' . $pn . '</span> &nbsp;';

    $centerPages .= '&nbsp; <a href="' . $currentUrl . '?pn=' . $add1 . '">' . $add1 . '</a> &nbsp;';

}

// This line sets the "LIMIT" range... the 2 values we place to choose a range of rows from database in our query

$limit = 'LIMIT ' .($pn - 1) * $itemsPerPage .',' .$itemsPerPage;

// Now we are going to run the same query as above but this time add $limit onto the end of the SQL syntax

// $sql2 is what we will use to fuel our while loop statement below

//$sql2 = mysql_query("SELECT * from imagegallery ORDER BY imagegallery_id ASC $limit");

$prefix = Mage::getConfig()->getTablePrefix();

$tblname=$prefix.'popupgalleryslider';

$sql2 = $connection->query("select * from $tblname ORDER BY id ASC $limit");



$paginationDisplay = ""; // Initialize the pagination output variable

// This code runs only if the last page variable is ot equal to 1, if it is only 1 page we require no paginated links to display

if ($lastPage != "1"){

    // This shows the user what page they are on, and the total number of pages

    $paginationDisplay .= 'Page <strong>' . $pn . '</strong> of ' . $lastPage. '&nbsp;  &nbsp;  &nbsp; ';

    // If we are not on page 1 we can place the Back button

    if ($pn != 1) {

        $previous = $pn - 1;

        $paginationDisplay .=  '&nbsp;  <a href="' . $currentUrl . '?pn=' . $previous . '"> Back</a> ';

    }

    // Lay in the clickable numbers display here between the Back and Next links

    $paginationDisplay .= '<span class="paginationNumbers">' . $centerPages . '</span>';

    // If we are not on the very last page we can place the Next button

    if ($pn != $lastPage) {

        $nextPage = $pn + 1;

        $paginationDisplay .=  '&nbsp;  <a href="' . $currentUrl . '?pn=' . $nextPage . '"> Next</a> ';

    }

}

?>
<ul id="items2">

<?php

$k=1;

$outputList = '';

$vz=1;

$i = 0;

$i = $i+1;

while($row1 = $sql2->fetch())

{

//print_r($row1);

$id = $row1["id"];

$firstname = $row1["url"];

$country = $row1["image"];

$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);

$img_src = $media_url.$country;

?>

    <li>

<div class="rpt-gallery">

    <a href="#gal-img<?php echo $k; ?>" class="popup-with-zoom-anim">

        <div class="gallery-img">

             <img src="<?php echo $img_src; ?>" height="<?php echo $gallery_imageheight; ?>" width="<?php echo $gallery_imagewidth; ?>">

        </div>

    </a>

    <div id ="gal-img<?php echo $k; ?>" class="mfp-hide"> <img src="<?php echo $img_src; ?>"  alt="bcard-large01"/> </div>

     <span><a href="<?php echo Mage::getBaseUrl().$row1["url"]; ?>"><?php echo $row1["title"]; ?></a></span>

</div>





    </li>

    <?php $k++; } ?>

</ul>
     <div class="pagination">
         <ul>
             <?php for($i=1;$i<=$lastPage;$i++){
                 ?>
                 <li <?php if($pn == $i): ?> class="active" <?php endif; ?>>
                     <a href="<?php echo $currentUrl."?pn=".$i; ?>"><?php echo $i; ?></a>
                 </li>
                 <?php
             } ?>
         </ul>
     </div>



<?php }

/* module type 1 close */



} else { ?>



<span style="color:red;">Enable ( MKS IMAGE GALLERY ) Module via Admin : = </span> <span style="color:black;">System -> Configuration->Mks Image gallery-> General Setting </span>



<?php } ?>

