<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Ced
 * @package     Ced_SocialLogin
 * @author 		CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   	Ced
 * @package    	Ced_SocialLogin
 * @author 		CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com>
 */
?>

    <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>" class="fb">
    <?php //echo $this->_getButtonText(); ?>
			<span class="<?php //echo $this->_getButtonClass(); ?>">
			<img src="<?php echo $this->getSkinUrl('ced_sociallogin/facebook/images/social_connect_fb.png'); ?>" />
			</span>Sign in with Facebook
    </a>   
