<?php
                $productAttribute = $_product->getResource()->getAttribute('quntity');
                $quntitylabel = $productAttribute->getStoreLabel(Mage::app()->getStore()->getName());
                $quantities = $_product->getAttributeText('quntity');
          ?>
<div class="prdct-control" id="product_view">
              <label class="required"><?php echo $quntitylabel; ?><em>*</em></label>
              <div class="control-box">
                 <div class="slct-dwopdd">
                   <select name="qty" id="qty"  title="<?php echo $this->__('Qty') ?>" tabindex="2" class="input-text qty chosen-select validate-select">
                    <option value="">Choose</option>
<?php foreach ($quantities as $quantity) { ?>
<?php $cart_quantity = $this->getProductDefaultQty() * 1 ?>
<option value="<?php echo $quantity; ?>"><?php echo $quantity; ?></option>
<?php } ?>
</select>
</div>
</div>
</div>