<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Ced
 * @package     Ced_SocialLogin
 * @author 		CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   	Ced
 * @package    	Ced_SocialLogin
 * @author 		CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com>
 */
?>
<!-- <div class="clearer"> 
		<a href="<?php //echo $this->escapeUrl($this->_getButtonUrl()); ?>">
		<?php //echo $this->_getButtonText(); ?>
			<div class="ced-sociallogin-google-inner <?php //echo $this->_getButtonClass(); ?>">
			</div>
        </a>	
</div> -->
<a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>" class="google">
    <?php //echo $this->_getButtonText(); ?>
			<span class="<?php //echo $this->_getButtonClass(); ?>">
			<img src="<?php echo $this->getSkinUrl('ced_sociallogin/google/images/google-icon.png'); ?>" />
			</span>Sign in with Google
			<i>+</i>
    </a>   