<?php
if(isset($_POST['sample_order']))
{




//    $_POST['state'] = "Yo ! Wri59";

    if(isset($_POST['g-recaptcha-response']))
    {
        $captcha=$_POST['g-recaptcha-response'];
    }

    if($captcha)
    {
        $captchaerr = 'Check box if you are not a robot.';
    }
    else
    {
        if($_POST['fname']==" " or $_POST['email']==" " or $_POST['zipcode']==" " or $_POST['address']==" " )
        {
            $pageURL = Mage::getUrl() . Mage::getSingleton('cms/page')->getIdentifier();
            Mage::app()->getFrontController()->getResponse()->setRedirect($pageURL);
        }
        else
        {
            $date = date("F j, Y, g:i a");
            $gen_contact = Mage::getStoreConfig('trans_email/ident_general/email');
            $to = "manish.wri59@webreinvent.com";
//            $to = $gen_contact;
            $subject = "Sample Order Request.";
            $txt = "First Name: ".$_POST['fname']."\n";
            $txt .= "Last Name: ".$_POST['lname']."\n";
            $txt .= "Email: ".$_POST['email']."\n";
            $txt .= "Company: ".$_POST['cmpy_name']."\n";
            $txt .= "Address: ".$_POST['address']."\n";
            $txt .= "Apt/Suite/Other: ".$_POST['aso']."\n";
            $txt .= "Country: ".$_POST['country_new']."\n";
            $txt .= "City: ".$_POST['city']."\n";

//            if($_POST['intrntnal_ship'])
//            {
//                $txt .= "State: ".$_POST['intrntnal_ship']."\n";
//            }
            if($_POST['country_new'] == 'US')
            {
                if(!empty($_POST['state_new']))
                {
                    $_POST['state'] = $_POST['state_new'];
                }
                else{
                    $_POST['state'] = " ";
                }

            }
            $txt .= "State: ".$_POST['state']."\n";

            $txt .= "Zip Code: ".$_POST['zipcode']."\n";
            $txt .= "Shipping Cost: ".$_POST['shping_cost']."\n";
            $txt .= "Requested Stocks: ".$_POST['mssg']."\n";

            $headers = "From:". $_POST['email'];

            $mail_succes =  mail($to,$subject,$txt,$headers);

            if($mail_succes)
            {
            $write = Mage::getSingleton('core/resource')->getConnection('core_write');
            }
            //$writeMethods = get_class_methods(get_class($write));
//foreach($writeMethods as $r){echo $r."\n";}

            $result = $write->insert("dealerinquiry", array(
                    "firstname" => $_POST['fname'],
                    "company" => $_POST['cmpy_name'],
                    "address" => $_POST['address'],
                    "city" => $_POST['city'],
                    "state" => 'State',
                    "state_new" => 'test',
                    "country" => $_POST['country_new'],
                    "zip" => $_POST['zipcode'],
                    "email" => $_POST['email'],
                    "storeid" => $_POST['shping_cost'],
                    "website" => $_POST['form_name'],
                    "desc" => $_POST['mssg'],
                    "iscustcreated" => 1,
                    "date_time" => $date,
                    "lstname" => $_POST['lname'],
                    "aso" => $_POST['aso']
                )
            );

            if($mail_succes)
            {
                $successUrl = Mage::getUrl('success_page');
                Mage::app()
                    ->getFrontController()
                    ->getResponse()
                    ->setRedirect($successUrl);
            }
            else
            {
                $successUrl = Mage::getUrl('home_page');
                Mage::app()
                    ->getFrontController()
                    ->getResponse()
                    ->setRedirect($successUrl);
            }
        }
    }
}



?>
<div class="sampletemplate-form">
    <h3>Get <strong>Samples</strong></h3>
    <div class="sample-inrform"><form id="oSPacket" method="post" name="order_sample_packet_form" action="<?php echo $_SERVER['PHP_SELF']; ?>">

            <div class="input-field"><label>First Name<sup>*</sup></label>
                <div class="inp-text"><input id="fname" class="inp-text-inpt required-entry validate-name" type="text" value="<?php echo $_POST['fname']; ?>" maxlength="20" placeholder="Enter your First Name" name="fname" /></div>
            </div>
            <div class="input-field"><label>Last Name<sup>*</sup></label>
                <div class="inp-text"><input id="lname" class="inp-text-inpt required-entry validate-name" type="text" value="<?php echo $_POST['lname']; ?>" maxlength="20" placeholder="Enter your Last Name" name="lname" /></div>
            </div>
            <div class="input-field"><label>Company</label>
                <div class="inp-text"><input id="cmpy_name" class="inp-text-inpt " type="text" value="<?php echo $_POST['cmpy_name']; ?>" maxlength="30" placeholder="Enter Company Name" name="cmpy_name" /></div>
            </div>
            <div class="input-field"><label>Street Address<sup>*</sup></label>
                <div class="inp-text"><input id="address" class="inp-text-inpt required-entry" type="text" value="<?php echo $_POST['address']; ?>" maxlength="50" placeholder="Enter your Address" name="address" /></div>
            </div>
            <div class="input-field"><label>Apt/Suite/Other</label>
                <div class="inp-text"><input id="aso" class="inp-text-inpt " type="text" value="<?php echo $_POST['aso']; ?>" placeholder="Enter your Apt/Suite/Other" maxlength="50" name="aso" /></div>
            </div>
            <div class="input-field"><label>Country<sup>*</sup></label>
                <div class="inp-text">
                    <?php $_countries = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false) ?>
                    <?php if (count($_countries) > 0): ?>
                        <select name="country_new" class="chosen-select required-entry" id="country_new" style="width: 100%;">
                            <!-- <option value="">– Please Select –</option>   -->
                            <?php if($_POST['sample_order'] == true && $_POST['country_new'] != ""){ ?>
                                <option value="<?php echo $_POST['country_new']; ?>" selected="selected"><?php echo $_POST['country_new']; ?></option>
                            <?php }else{ ?>
                                <option value=""> – Please Select – </option>
                            <?php } ?>
                            <?php foreach($_countries as $_country): ?>
                                <option value="<?php echo $_country['value'] ?>">
                                    <?php echo $_country['label'] ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>


                </div>
            </div>

            <div class="input-field"><label>State/Province<sup>*</sup></label>
                <div class="inp-text">

                    <input id="state" class="inp-text-inpt validate-state" type="text" maxlength="20" value="<?php echo $_POST['state']; ?>" placeholder="State/Province" name="state" />

                    <select id="region_id" style="display:none;" style="width:100%;" name="state_new" title="<?php echo $this->__('State/Province') ?>" class="chosen-select">
                        <option value=""><?php echo $this->__('Please select state or province') ?></option>
                        <?php
                        $regions = Mage::getModel('directory/country')->load('US')->getRegions();
                        foreach($regions as $region)
                        {
                            echo "<option value=".$region[name].">".$region['name'] . "</option>";
                        }
                        ?>
                    </select>
                </div>

            </div>

            <div class="input-field"><label>City<sup>*</sup></label>
                <div class="inp-text"><input id="city" class="inp-text-inpt required-entry validate-city" type="text" value="<?php echo $_POST['city']; ?>" placeholder="Enter your City" maxlength="20" name="city" /></div>
            </div>
            <!--    <div class="input-field vv-state"><label>State<sup>*</sup></label>
                   <div class="inp-text"><select id="state" value="state" class="chosen-select validate-select" style="width: 100%;" name="intrntnal_ship"></select>
                       <script type="text/javascript">// <![CDATA[
                           print_country("country");
                           // ]]></script>
                   </div>
               </div> -->
            <div class="input-field"><label>Zip Code<sup>*</sup></label>
                <div class="inp-text"><input id="zipcode" class="inp-text-inpt required-entry validate-zipcode" type="text" value="<?php echo $_POST['zipcode']; ?>" maxlength="8" placeholder="Enter zip code" name="zipcode" /></div>
            </div>
            <div class="input-field"><label>Email<sup>*</sup></label>
                <div class="inp-text"><input id="email" class="inp-text-inpt required-entry validate-emailid" type="text" value="<?php echo $_POST['email']; ?>" maxlength="50" placeholder="Enter your Email" name="email" /></div>
            </div>
            <div class="input-field"><label>Requested Stocks</label>
                <div class="inp-text"><textarea id="mssg" class="inp-txt-area" name="mssg" maxlength="100" placeholder="Please list stocks as you would like to see in your sample packet"><?php echo $_POST['mssg']; ?></textarea></div>
            </div>
            <div class="input-field vv-shippingcost"><label>Shipping Cost<sup>*</sup></label>
                <div class="inp-text">
                    <select class="chosen-select required-entry validate-select" style="width: 100%;" name="shping_cost">
                        <!-- <option value="">Choose Packets</option> -->

                        <option value=""> Choose Packets </option>

                        <option "<?php if($_POST['shping_cost'] == "US Shipping-$10"){ ?>" selected "<?php }?>" value="US Shipping-$10">US Shipping-$10</option>
                        <option "<?php if($_POST['shping_cost'] == "International Shipping-$15"){ ?>" selected "<?php }?>" value="International Shipping-$15">International Shipping-$15</option>
                    </select></div>
                <input class="inp-text" type="hidden" value="Order Sample Packet" name="form_name" />
                <div class="input-field">&nbsp;</div>
                <p><strong>NOTE:</strong> US sample packets will be $10, International will be $15. Free ground shipping.</p>
            </div>
            <div class="input-field captcha-fld"><label><p></p></label>


                <div class="inp-text">
                    <div class="g-recaptcha" data-sitekey="6LfmyB4TAAAAAKnRG-pri2okMiatW2TmLx8XmFIU"></div>
                    <span style="color:red;"><?php echo $captchaerr; ?></span>
                </div>


            </div>
            <div class="form-submit">&nbsp;</div>
            <div class="form-submit"><input class="submit-btn" type="submit" value="Add to Cart" name="sample_order" /></div>
        </form></div>
</div>
<script type="text/javascript">
    Validation.add('validate-name', 'Please use letters only, numbers are optional.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(?=.*[a-zA-Z].*)([-_a-zA-Z0-9 ]+)$/i.test(v)
    })
    Validation.add('validate-zipcode', 'Please enter valid zipcode.', function(v) {
        return Validation.get('IsEmpty').test(v) || /[a-zA-Z0-9-)( ]{5,7}$/i.test(v)
    })
    Validation.add('validate-emailid', 'Please enter a valid email address.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/i.test(v)
    });
    Validation.add('validate-city', 'Please enter a valid city.', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(?:[a-zA-Z]+(?:[.'\-,])?\s?)+$/i.test(v)
    })
    Validation.add('validate-state', 'Please enter valid state.', function(v) {
        return Validation.get('IsEmpty').test(v) || /[a-zA-Z0-9-)(.' ]$/i.test(v)
    })
</script>

