<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="utf-8">

<meta charset="utf-8">



<?php echo $this->getChildHtml('head'); ?>
<link href="<?php echo $this->getSkinUrl('css/jquery-filestyle.css') ?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->getSkinUrl('css/contact-style.css') ?>" rel="stylesheet" type="text/css"/>

</head>

<body <?php echo $this->getBodyClass()?' class=" drawer drawer-left drawer-navbar drawer-fixed site-base drawer-close '.$this->getBodyClass().'"':'' ?>>



<?php echo $this->getChildHtml('header'); ?>



<!--breadcrum/banner-->



<div class="main_con mrg-tp-var">

  <div class="container"> 

    <!--breadcrum-part-->

    

    <div class="breadcrum-con bg-grey">

     <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>

    </div>

    <!--/breadcrum-part--> 

  </div>

</div>



<!--/breadcrum/banner--> 



<!--middle-content-->

<div class="main_con">

  <div class="container">

<div class="contact-formcon">
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="row-fluid">
<div class="span6">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-information')->toHtml(); ?>
</div>
<div class="span6">
<div class="contact-usform">
<h3><?php echo $this->__('Contact Us <strong>Form</strong>') ?></h3>
<div class="cont-support-form">
    <form id="ConatctForm" method="post" enctype="multipart/form-data">

         <div class="input-field">
         <label><?php echo $this->__('First Name') ?><span>*</span></label>  
         <div class="inp-text">    
         <input name="fname" id="fname" title="<?php echo $this->__('First Name') ?>" value="" class="inp-text-inpt required-entry validate-alpha" type="text"  />
         </div>
         </div>

         <div class="input-field">
         <label><?php echo $this->__('Last Name') ?></label>  
         <div class="inp-text">    
         <input name="lname" id="lname" title="<?php echo $this->__('Last Name') ?>" value="" class="inp-text-inpt validate-alpha" type="text"  />
         </div>
         </div>

            <div class="input-field">
         <label><?php echo $this->__('Email') ?><span>*</span></label>
         <div class="inp-text">
         <input name="email" id="email" title="<?php echo $this->__('Email') ?>" value="" class="inp-text-inpt required-entry validate-email" type="text" />
         </div>
         </div>
          
         
         
           <div class="input-field">
         <label><?php echo $this->__('Phone') ?></label>
         <div class="inp-text">
         <input name="telephone" id="telephone" title="<?php echo $this->__('Telephone') ?>" value="" class="inp-text-inpt" type="text" />
         </div>
         </div>

          <div class="input-field">
         <label><?php echo Mage::helper('contacts')->__('Company') ?></label>
           <div class="inp-text">
         <input name="company" id="company" title="<?php echo $this->__('Company') ?>" value="" class="inp-text-inpt" type="text"/>
         </div>
         </div>
          <div class="input-field">
         <label><?php echo $this->__('Order No') ?></label>
           <div class="inp-text">
         <input name="order_no" id="order_no" placeholder="Order Number (if applicable)" title="<?php echo $this->__('Order No') ?>" value="" class="inp-text-inpt" type="text"/>
         </div>
         </div>
          
          <div class="input-field wd-fl" >
         <label><?php echo $this->__('File Upload') ?></label>
          <input type="file" id="brs-img1" name="imagePreview" >
         </div>


           <div class="input-field">
         <label><?php echo $this->__('Comment') ?><span>*</span></label>
           <div class="inp-text">
         <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="inp-txt-area required-entry  " cols="5" rows="3" ></textarea>
         </div>
         </div>
            <input type="hidden" name="form_name" value="Contact Us Form">
         <div class="input-field mndrty">  
            <input type="hidden" name="form_name" value="Contact Us Form">
            <label><?php echo $this->__('Fields Required') ?><span>*</span></label> 
             <div class="form-submit">
             <input class="submit-btn" type="submit" value="Submit" name="conatctform"/></div>
          </div>
         </form>
           </div>
</div>
</div>

</div>
</div>


  </div>

</div>






<!--/middle-content--> 



<!--newsletter-->

<div class="main_con bg-dk2e2e2e ">

  <div class="container">

    <div class="newsletter">

         <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>

    </div>

  </div>

</div>

<!--/newsletter-->





<?php 

         if(isset($_POST['conatctform']))

       { 
          
                   if($_POST['fname']==" "  or $_POST['email']==" " or $_POST['comment']==" ")
                  {
                            $pageURL = Mage::getUrl() . Mage::getSingleton('cms/page')->getIdentifier();
                            Mage::app()->getFrontController()->getResponse()->setRedirect($pageURL);
                  }
                  else
                  { 


                         $fileName  = $_FILES['imagePreview']['name'];
                         $imagePreview = 'banner'.'/'.$_FILES['imagePreview']['name'];
                         $media_path1  = Mage::getBaseDir('media') . DS . 'banner' . DS.$fileName;

 
                        $to = "vishal.v@webreinvent.com";
                        $subject = "Your password with attachment test";
                        $from = "admin@itservice.com";
                        $headers = "From: $from\r\n";
                        $headers .= "MIME-Version: 1.0\r\n"
                          ."Content-Type: multipart/mixed; boundary=\"1a2a3a\"";
                         
                        $message .= "If you can see this MIME than your client doesn't accept MIME types!\r\n"
                          ."--1a2a3a\r\n";
                         
                        $message .= "Content-Type: text/html; charset=\"iso-8859-1\"\r\n"
                          ."Content-Transfer-Encoding: 7bit\r\n\r\n"
                          ."hey my <b>good</b> friend here is a picture of me"
                          ."<p>Your password is : <span style='color:red'><b>User@1$#!</b></span></p> \r\n"
                          ."--1a2a3a\r\n";


                         
                        $file = file_get_contents("https://pixabay.com/static/uploads/photo/2015/10/01/21/39/background-image-967820_960_720.jpg");
                         
                        $message .= "Content-Type: image/jpg; name=\"picture.jpg\"\r\n"
                          ."Content-Transfer-Encoding: base64\r\n"
                          ."Content-disposition: attachment; file=\"picture.jpg\"\r\n"
                          ."\r\n"
                          .chunk_split(base64_encode($file))
                          ."--1a2a3a--";

                        

                           $success_mail = mail($to,$subject,$message,$headers);

                           if($success_mail)
                           {

                                 $write = Mage::getSingleton('core/resource')->getConnection('core_write');

                                 $writeMethods = get_class_methods(get_class($write));

                                 $result = $write->insert(

                            "dealerinquiry", 

                           array("firstname" => $_POST['fname'],"phone" => $_POST['telephone'], "email" => $_POST['email'], "website" => $_POST['form_name'], "desc" => $_POST['comment'], "iscustcreated" => 1, "websiteid" => $_POST['order_no'], "imagePreview" => $imagePreview, "lstname" => $_POST['lname'])

                           ); 

                                  $successUrl = Mage::getUrl('success_page');
                                  Mage::app()->getFrontController()->getResponse()->setRedirect($successUrl);
                            }   
                 } 

       }

?>


<?php echo $this->getChildHtml('footer'); ?>

<script src="<?php echo $this->getSkinUrl('js/jquery-filestyle.js') ?>"></script> 
 <script type="text/javascript">
    //< ![CDATA[
       var myForm= new VarienForm('ConatctForm', true);
    //]]>
</script>

    <!--/search-btn-toggle --> 
 <script type="text/javascript">
 jQuery('#brs-img1').jfilestyle({
      
        buttonText: "Browse"

      });

</script>
</body>


</html>